name: build

on:
  push:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    container: thomasweise/docker-texlive-full
    steps:
    - uses: actions/checkout@v2
    - name: Download github icon
      run: wget https://www.dropbox.com/s/v3jj5m8a0c42edc/github.pdf
    - name: Download gitlab icon
      run: wget https://gitlab.com/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png -O gitlab.png
    - name: Download picture
      run: wget https://www.dropbox.com/s/qtxy393y6u64lw0/picture.jpg
    - name: Download youtube icon
      run: wget https://www.dropbox.com/s/gdrf2iusk0wuuua/youtube.png
    - name: Download extref icon
      run: wget https://www.brandeps.com/icon-download/S/Share-square-outlined-01.eps -O external.eps
    - name: Build
      run: for i in 1 2 3 ; do pdflatex main.tex && biber main ; done
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: cv
        path: main.pdf

  release-gh-pages:
    runs-on: ubuntu-latest
    needs: build-latex
    steps:
      - name: Make directory
        run: mkdir html
      - name: Set file name
        run: echo "CV_PDF_NAME=resume_marco_tiraboschi.pdf" >> $GITHUB_ENV
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: cv
      - name: Display structure of downloaded files
        run: ls -R
      - name: Include pdf
        run: cp main.pdf html/${{ env.CV_PDF_NAME }}
      - name: No Jekyll
        run: touch html/.nojekyll
      - name: Autoredirect from home to pdf
        run: echo '<meta http-equiv="Refresh", content="0; url=${{ env.CV_PDF_NAME }}" />' > html/index.html
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: html
